// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Taj_Plazza.Core.DataAcess;

#nullable disable

namespace TajePlazza.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250519121843_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Taj_Plazza.Core.Models.Utilisateur", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateInscription")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstActif")
                        .HasColumnType("bit");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("Taje__Plazza.Domain.Models.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroDeTelephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UtilisateurId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Taje__Plazza.Domain.Models.Equipement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuantiteDisponible")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Equipements");
                });

            modelBuilder.Entity("Taje__Plazza.Domain.Models.Espace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Capacite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EquipementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeEspace")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EquipementId");

                    b.ToTable("Espaces");
                });

            modelBuilder.Entity("Taje__Plazza.Domain.Models.Evenement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateEvenement")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EspaceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeEvenement")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("EspaceId");

                    b.ToTable("Evenements");
                });

            modelBuilder.Entity("Taje__Plazza.Domain.Models.Facture", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateDePayement")
                        .HasColumnType("datetime2");

                    b.Property<string>("MontantTotal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TypeDePayement")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReservationId");

                    b.ToTable("Factures");
                });

            modelBuilder.Entity("Taje__Plazza.Domain.Models.LocationDEquipement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateDeLocation")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EquipementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EvenementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipementId");

                    b.HasIndex("EvenementId");

                    b.ToTable("LocationDEquipements");
                });

            modelBuilder.Entity("Taje__Plazza.Domain.Models.MaintenanceDEquipement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateDebutMaintenance")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFinMaintenance")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EquipementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EstTerminee")
                        .HasColumnType("bit");

                    b.Property<string>("TypeMaintenance")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EquipementId");

                    b.ToTable("MaintenanceDEquipements");
                });

            modelBuilder.Entity("Taje__Plazza.Domain.Models.Personnel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UtilisateurId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("Personnels");
                });

            modelBuilder.Entity("Taje__Plazza.Domain.Models.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateReservation")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EvenementId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("EvenementId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Taje__Plazza.Domain.Models.Client", b =>
                {
                    b.HasOne("Taj_Plazza.Core.Models.Utilisateur", "Utilisateur")
                        .WithMany("Clients")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("Taje__Plazza.Domain.Models.Espace", b =>
                {
                    b.HasOne("Taje__Plazza.Domain.Models.Equipement", "Equipement")
                        .WithMany("Espaces")
                        .HasForeignKey("EquipementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipement");
                });

            modelBuilder.Entity("Taje__Plazza.Domain.Models.Evenement", b =>
                {
                    b.HasOne("Taje__Plazza.Domain.Models.Client", "Client")
                        .WithMany("Evenements")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Taje__Plazza.Domain.Models.Espace", "Espace")
                        .WithMany("Evenements")
                        .HasForeignKey("EspaceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Espace");
                });

            modelBuilder.Entity("Taje__Plazza.Domain.Models.Facture", b =>
                {
                    b.HasOne("Taje__Plazza.Domain.Models.Reservation", "Reservation")
                        .WithMany("Factures")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("Taje__Plazza.Domain.Models.LocationDEquipement", b =>
                {
                    b.HasOne("Taje__Plazza.Domain.Models.Equipement", "Equipement")
                        .WithMany("LocationDEquipements")
                        .HasForeignKey("EquipementId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Taje__Plazza.Domain.Models.Evenement", "Evenement")
                        .WithMany("LocationDequipements")
                        .HasForeignKey("EvenementId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Equipement");

                    b.Navigation("Evenement");
                });

            modelBuilder.Entity("Taje__Plazza.Domain.Models.MaintenanceDEquipement", b =>
                {
                    b.HasOne("Taje__Plazza.Domain.Models.Equipement", "Equipement")
                        .WithMany("MaintenanceDEquipements")
                        .HasForeignKey("EquipementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipement");
                });

            modelBuilder.Entity("Taje__Plazza.Domain.Models.Personnel", b =>
                {
                    b.HasOne("Taj_Plazza.Core.Models.Utilisateur", "Utilisateur")
                        .WithMany("Personnels")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("Taje__Plazza.Domain.Models.Reservation", b =>
                {
                    b.HasOne("Taje__Plazza.Domain.Models.Client", "Client")
                        .WithMany("Reservations")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Taje__Plazza.Domain.Models.Evenement", "Evenement")
                        .WithMany("Reservations")
                        .HasForeignKey("EvenementId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Evenement");
                });

            modelBuilder.Entity("Taj_Plazza.Core.Models.Utilisateur", b =>
                {
                    b.Navigation("Clients");

                    b.Navigation("Personnels");
                });

            modelBuilder.Entity("Taje__Plazza.Domain.Models.Client", b =>
                {
                    b.Navigation("Evenements");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("Taje__Plazza.Domain.Models.Equipement", b =>
                {
                    b.Navigation("Espaces");

                    b.Navigation("LocationDEquipements");

                    b.Navigation("MaintenanceDEquipements");
                });

            modelBuilder.Entity("Taje__Plazza.Domain.Models.Espace", b =>
                {
                    b.Navigation("Evenements");
                });

            modelBuilder.Entity("Taje__Plazza.Domain.Models.Evenement", b =>
                {
                    b.Navigation("LocationDequipements");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("Taje__Plazza.Domain.Models.Reservation", b =>
                {
                    b.Navigation("Factures");
                });
#pragma warning restore 612, 618
        }
    }
}
